version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    restart: always
    env_file: .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer:latest
    container_name: fastapi-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db


volumes:
  postgres_data:
