"""update journey table

Revision ID: 218eee8f3658
Revises: 1a59ddbde541
Create Date: 2025-10-16 09:57:11.452557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218eee8f3658'
down_revision: Union[str, Sequence[str], None] = '1a59ddbde541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('our_journey', sa.Column('story_subtitle', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('story_description', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('story_img_url', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('vision_description', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('mission_description', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('mission_vision_img_url', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('value_description', sa.String(), nullable=True))
    op.add_column('our_journey', sa.Column('our_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('our_journey', 'title')
    op.drop_column('our_journey', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('our_journey', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('our_journey', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('our_journey', 'our_values')
    op.drop_column('our_journey', 'value_description')
    op.drop_column('our_journey', 'mission_vision_img_url')
    op.drop_column('our_journey', 'mission_description')
    op.drop_column('our_journey', 'vision_description')
    op.drop_column('our_journey', 'story_img_url')
    op.drop_column('our_journey', 'story_description')
    op.drop_column('our_journey', 'story_subtitle')
    # ### end Alembic commands ###
