"""migration_team_lang

Revision ID: 3ba66f1dcd0e
Revises: 9350ebc8bebf
Create Date: 2025-10-27 11:07:24.856381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba66f1dcd0e'
down_revision: Union[str, Sequence[str], None] = '9350ebc8bebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('name_ar', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('name_de', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('role_ar', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('role_de', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('description_ar', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('description_de', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'description_de')
    op.drop_column('teams', 'description_ar')
    op.drop_column('teams', 'role_de')
    op.drop_column('teams', 'role_ar')
    op.drop_column('teams', 'name_de')
    op.drop_column('teams', 'name_ar')
    # ### end Alembic commands ###
