"""update_new_table

Revision ID: 9206580b831a
Revises: 9ff256c4ed15
Create Date: 2025-10-15 12:45:59.203176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9206580b831a'
down_revision: Union[str, Sequence[str], None] = '9ff256c4ed15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('feature_news', sa.Boolean(), nullable=True))
    op.drop_column('news', 'subtitle')
    op.drop_column('news', 'photo_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('photo_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('subtitle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news', 'feature_news')
    # ### end Alembic commands ###
