"""add lang categories

Revision ID: 9350ebc8bebf
Revises: e0c67a72cc4b
Create Date: 2025-10-26 15:32:39.576546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9350ebc8bebf'
down_revision: Union[str, Sequence[str], None] = 'e0c67a72cc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_ar', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('name_de', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_de')
    op.drop_column('categories', 'name_ar')
    # ### end Alembic commands ###
