"""Update Product model with new fields and photo link replacement

Revision ID: 9ff256c4ed15
Revises: 7dc7c512c5ba
Create Date: 2025-10-13 15:39:18.892216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff256c4ed15'
down_revision: Union[str, Sequence[str], None] = '7dc7c512c5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('feature_product', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('visible', sa.Boolean(), nullable=True))
    op.drop_column('products', 'photo_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'visible')
    op.drop_column('products', 'feature_product')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
