"""add new_multiLanguage2 

Revision ID: c0b975bb7afe
Revises: f7653894a81e
Create Date: 2025-10-22 09:34:16.357655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b975bb7afe'
down_revision: Union[str, Sequence[str], None] = 'f7653894a81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title_ar', sa.String(), nullable=True))
    op.add_column('news', sa.Column('title_de', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title_de')
    op.drop_column('news', 'title_ar')
    # ### end Alembic commands ###
