"""product lang

Revision ID: dd2ba848b929
Revises: 3ba66f1dcd0e
Create Date: 2025-10-29 14:21:21.316746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2ba848b929'
down_revision: Union[str, Sequence[str], None] = '3ba66f1dcd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_ar', sa.String(), nullable=True))
    op.add_column('products', sa.Column('name_de', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description_ar', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description_de', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_de')
    op.drop_column('products', 'description_ar')
    op.drop_column('products', 'name_de')
    op.drop_column('products', 'name_ar')
    # ### end Alembic commands ###
