"""add name to paranter

Revision ID: e0c67a72cc4b
Revises: c0b975bb7afe
Create Date: 2025-10-26 10:45:01.898613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c67a72cc4b'
down_revision: Union[str, Sequence[str], None] = 'c0b975bb7afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('name_ar', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('name_de', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'name_de')
    op.drop_column('partners', 'name_ar')
    # ### end Alembic commands ###
