"""add new_multiLanguage 

Revision ID: f7653894a81e
Revises: a779465f2342
Create Date: 2025-10-21 14:44:16.249469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7653894a81e'
down_revision: Union[str, Sequence[str], None] = 'a779465f2342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('description_ar', sa.String(), nullable=True))
    op.add_column('news', sa.Column('description_de', sa.String(), nullable=True))
    op.add_column('news', sa.Column('content_ar', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('content_de', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'content_de')
    op.drop_column('news', 'content_ar')
    op.drop_column('news', 'description_de')
    op.drop_column('news', 'description_ar')
    # ### end Alembic commands ###
